export const expectedScreenshotItems = [
  "first-visit-intro/phrase",
  "first-visit-intro/gap",
  "first-visit-intro/intro-cursor",
  "first-visit-intro/intro-typed",
  "first-visit-intro/name-cursor",
  "first-visit-intro/phonetics",
  "first-visit-intro/prompt-cursor",
  "first-visit-intro/prompt-typed",
  "first-visit-intro/button",
  "consent-clickwrap/regular",
  "consent-clickwrap/manage",
  "consent-clickwrap/manage-analytics-off",
  "privacy-policy",
  "tracking-notice",
  "terms-of-use",
  "hero",
  "portfolio/page-1",
  "portfolio/page-2",
  "project-chat-page",
  "tree/linkedin",
  "tree/github",
  "tree/phone",
  "tree/email",
  "tree/devpost",
  "tree/portfolio",
  "about/business-card-front",
  "about/business-card-back",
  "about/timeline",
  "activity/github",
  "activity/linkedin",
  "admin-dashboard/bio",
  "admin-dashboard/projects",
  "admin-dashboard/skills",
] as const;

export const viewportNames = ["desktop", "mobile"] as const;
