DO $migration$
DECLARE
	target_schema text := pg_catalog.current_schema();
	audit_owner_role text := 'portfolio_audit_owner';
	audit_operator_role text := 'portfolio_compensation_operator';
	migration_executor_role text := current_user;
	relation_name text;
	key_columns text[];
	trigger_arguments text;
BEGIN
	IF target_schema IS NULL THEN
		RAISE EXCEPTION 'Portfolio audit migration requires an explicit target schema';
	END IF;
	IF (session_user <> 'portfolio_migrator_login'
		OR current_user <> 'portfolio_migrator')
		AND pg_catalog.lower(COALESCE(
			pg_catalog.current_setting('portfolio.test_admin_migration', true),
			'off'
		)) NOT IN ('1', 'on', 'true')
		AND EXISTS (
			SELECT 1 FROM pg_catalog.pg_roles
			WHERE rolname IN ('portfolio_migrator_login', 'portfolio_migrator')
			HAVING count(*) = 2
		)
	THEN
		RAISE EXCEPTION 'Portfolio audit migration requires portfolio_migrator_login SET ROLE portfolio_migrator';
	END IF;
	IF EXISTS (
		SELECT 1
		FROM pg_catalog.pg_roles AS role
		WHERE role.rolname IN (audit_owner_role, audit_operator_role)
			AND (
				role.rolcanlogin
				OR role.rolinherit
				OR role.rolsuper
				OR role.rolcreatedb
				OR role.rolcreaterole
				OR role.rolreplication
				OR role.rolbypassrls
			)
	) THEN
		RAISE EXCEPTION 'Portfolio audit owner or operator role attributes are unsafe';
	END IF;
	IF current_user = 'portfolio_migrator'
		AND (NOT pg_catalog.pg_has_role(current_user, audit_owner_role, 'SET')
		OR NOT pg_catalog.pg_has_role(current_user, audit_operator_role, 'SET')
		)
	THEN
		RAISE EXCEPTION 'Portfolio migrator audit/compensation memberships must be provisioned before migration';
	END IF;

	EXECUTE pg_catalog.format($ddl$
		CREATE TABLE %1$I.database_audit_chain_heads (
			chain_name text PRIMARY KEY,
			head_hash text NOT NULL CHECK (head_hash ~ '^[0-9a-f]{64}$'),
			entry_count bigint DEFAULT 0 NOT NULL CHECK (entry_count >= 0),
			updated_at timestamp with time zone DEFAULT pg_catalog.clock_timestamp() NOT NULL,
			CONSTRAINT database_audit_chain_heads_name_check CHECK (chain_name = 'portfolio')
		)
	$ddl$, target_schema);

	EXECUTE pg_catalog.format($ddl$
		CREATE TABLE %1$I.database_mutation_audit (
			audit_id uuid PRIMARY KEY DEFAULT pg_catalog.gen_random_uuid(),
			sequence_number bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE,
			transaction_id text NOT NULL,
			schema_name text NOT NULL CHECK (schema_name = 'portfolio'),
			table_name text NOT NULL CHECK (table_name ~ '^[a-z_][a-z0-9_]{0,62}$'),
			operation text NOT NULL CHECK (operation IN ('INSERT', 'UPDATE', 'DELETE')),
			row_key jsonb NOT NULL CHECK (pg_catalog.jsonb_typeof(row_key) = 'object'),
			changed_columns text[] NOT NULL CHECK (pg_catalog.cardinality(changed_columns) > 0),
			before_redacted jsonb,
			after_redacted jsonb,
			before_digest text NOT NULL CHECK (before_digest ~ '^[0-9a-f]{64}$'),
			after_digest text NOT NULL CHECK (after_digest ~ '^[0-9a-f]{64}$'),
			database_session_user text NOT NULL,
			database_current_user text NOT NULL,
			request_id text NOT NULL CHECK (pg_catalog.length(request_id) BETWEEN 1 AND 160),
			trace_id text NOT NULL CHECK (pg_catalog.length(trace_id) BETWEEN 1 AND 160),
			actor_kind text NOT NULL CHECK (pg_catalog.length(actor_kind) BETWEEN 1 AND 64),
			actor_id text NOT NULL CHECK (pg_catalog.length(actor_id) BETWEEN 1 AND 160),
			operation_context text NOT NULL CHECK (pg_catalog.length(operation_context) BETWEEN 1 AND 160),
			correlation_id text CHECK (correlation_id IS NULL OR pg_catalog.length(correlation_id) BETWEEN 1 AND 160),
			causation_id text CHECK (causation_id IS NULL OR pg_catalog.length(causation_id) BETWEEN 1 AND 160),
			release_id text NOT NULL CHECK (pg_catalog.length(release_id) BETWEEN 1 AND 160),
			authentication_assertion_digest text
				CHECK (
					authentication_assertion_digest IS NULL
					OR authentication_assertion_digest ~ '^[0-9a-f]{64}$'
				),
			compensation_of uuid REFERENCES %1$I.database_mutation_audit(audit_id),
			previous_hash text NOT NULL CHECK (previous_hash ~ '^[0-9a-f]{64}$'),
			entry_hash text NOT NULL UNIQUE CHECK (entry_hash ~ '^[0-9a-f]{64}$'),
			occurred_at timestamp with time zone NOT NULL
		)
	$ddl$, target_schema);

	EXECUTE pg_catalog.format($ddl$
		CREATE TABLE %1$I.database_compensation_payloads (
			audit_id uuid PRIMARY KEY REFERENCES %1$I.database_mutation_audit(audit_id),
			before_state jsonb,
			after_state jsonb,
			created_at timestamp with time zone DEFAULT pg_catalog.clock_timestamp() NOT NULL,
			expires_at timestamp with time zone
				DEFAULT (pg_catalog.clock_timestamp() + interval '7 days') NOT NULL,
			CONSTRAINT database_compensation_payloads_retention_check
				CHECK (expires_at > created_at)
		)
	$ddl$, target_schema);

	-- The audit expansion begins in compatibility mode so the already-deployed
	-- 37abdbd7a15f revision remains writable while every mutation is still audited.
	-- Contraction is performed only by a later successful release after 48 hours.
	EXECUTE pg_catalog.format($ddl$
		CREATE TABLE %1$I.database_audit_activation (
			singleton boolean PRIMARY KEY DEFAULT true CHECK (singleton),
			mode text NOT NULL DEFAULT 'compatibility' CHECK (mode IN ('compatibility', 'enforced')),
			compatibility_started_at timestamp with time zone,
			compatibility_release_sha text CHECK (
				compatibility_release_sha IS NULL OR compatibility_release_sha ~ '^[0-9a-f]{40}$'
			),
			enforced_at timestamp with time zone,
			enforced_release_sha text CHECK (
				enforced_release_sha IS NULL OR enforced_release_sha ~ '^[0-9a-f]{40}$'
			),
			CONSTRAINT database_audit_activation_mode_state CHECK (
				(mode = 'compatibility' AND enforced_at IS NULL AND enforced_release_sha IS NULL)
				OR (mode = 'enforced' AND enforced_at IS NOT NULL AND enforced_release_sha IS NOT NULL)
			)
		)
	$ddl$, target_schema);
	EXECUTE pg_catalog.format($ddl$
		CREATE TABLE %1$I.database_audit_releases (
			release_sha text PRIMARY KEY CHECK (release_sha ~ '^[0-9a-f]{40}$'),
			image_digest text NOT NULL CHECK (image_digest ~ '^sha256:[0-9a-f]{64}$'),
			successful_at timestamp with time zone NOT NULL DEFAULT pg_catalog.clock_timestamp(),
			UNIQUE (image_digest)
		)
	$ddl$, target_schema);
	EXECUTE pg_catalog.format(
		'INSERT INTO %I.database_audit_activation (singleton) VALUES (true)',
		target_schema
	);

	EXECUTE pg_catalog.format(
		'CREATE INDEX database_mutation_audit_relation_row_idx ON %I.database_mutation_audit (schema_name, table_name, row_key, sequence_number)',
		target_schema
	);
	EXECUTE pg_catalog.format(
		'CREATE INDEX database_mutation_audit_compensation_idx ON %I.database_mutation_audit (compensation_of) WHERE compensation_of IS NOT NULL',
		target_schema
	);

	EXECUTE pg_catalog.format(
		'INSERT INTO %I.database_audit_chain_heads (chain_name, head_hash) VALUES ($1, $2)',
		target_schema
	) USING 'portfolio', pg_catalog.repeat('0', 64);

	-- These two trigger routines intentionally use pg_catalog trigger-routine identities.
	-- Every trigger call is schema-qualified, so PostgreSQL retains the target schema in
	-- pg_get_triggerdef for both the private schema and its transaction-local reconstruction.
	EXECUTE pg_catalog.format($ddl$
		CREATE FUNCTION %1$I.unique_key_recheck()
		RETURNS trigger
		LANGUAGE plpgsql
		SECURITY DEFINER
		SET search_path = pg_catalog
		SET TimeZone = 'UTC'
		AS $function$
		BEGIN
			IF TG_TABLE_NAME = 'database_mutation_audit'
				AND TG_OP = 'INSERT'
				AND pg_catalog.pg_trigger_depth() > 1
			THEN
				RETURN NEW;
			END IF;
			IF TG_TABLE_NAME = 'database_audit_chain_heads'
				AND TG_OP = 'UPDATE'
				AND pg_catalog.pg_trigger_depth() > 1
			THEN
				RETURN NEW;
			END IF;
			RAISE EXCEPTION USING
				ERRCODE = 'PDA10',
				MESSAGE = 'database audit history is immutable';
		END
		$function$
	$ddl$, target_schema);

	EXECUTE pg_catalog.format($ddl$
		CREATE FUNCTION %1$I.suppress_redundant_updates_trigger()
		RETURNS trigger
		LANGUAGE plpgsql
		SECURITY DEFINER
		SET search_path = pg_catalog
		SET TimeZone = 'UTC'
		AS $function$
		DECLARE
			audit_identifier uuid := pg_catalog.gen_random_uuid();
			sequence_identifier bigint;
			transaction_identifier text := pg_catalog.pg_current_xact_id()::text;
			occurred timestamp with time zone := pg_catalog.clock_timestamp();
			old_value jsonb := CASE WHEN TG_OP = 'INSERT' THEN NULL ELSE pg_catalog.to_jsonb(OLD) END;
			new_value jsonb := CASE WHEN TG_OP = 'DELETE' THEN NULL ELSE pg_catalog.to_jsonb(NEW) END;
			source_value jsonb := CASE WHEN TG_OP = 'DELETE' THEN pg_catalog.to_jsonb(OLD) ELSE pg_catalog.to_jsonb(NEW) END;
			key_value jsonb := '{}'::jsonb;
			changed text[];
			before_value jsonb;
			after_value jsonb;
			before_redacted_value jsonb;
			after_redacted_value jsonb;
			before_hash text;
			after_hash text;
			prior_hash text;
			calculated_hash text;
			argument_index integer;
			audit_request_id text := NULLIF(pg_catalog.current_setting('portfolio_audit.request_id', true), '');
			audit_trace_id text := NULLIF(pg_catalog.current_setting('portfolio_audit.trace_id', true), '');
			audit_actor_kind text := NULLIF(pg_catalog.current_setting('portfolio_audit.actor_kind', true), '');
			audit_actor_id text := NULLIF(pg_catalog.current_setting('portfolio_audit.actor_id', true), '');
			audit_operation text := NULLIF(pg_catalog.current_setting('portfolio_audit.operation', true), '');
			audit_correlation_id text := NULLIF(pg_catalog.current_setting('portfolio_audit.correlation_id', true), '');
			audit_causation_id text := NULLIF(pg_catalog.current_setting('portfolio_audit.causation_id', true), '');
			audit_release_id text := NULLIF(pg_catalog.current_setting('portfolio_audit.release_id', true), '');
			audit_assertion_digest text := NULLIF(pg_catalog.current_setting('portfolio_audit.authentication_assertion_digest', true), '');
			compensated_audit_id uuid;
			audit_mode text;
		BEGIN
			IF pg_catalog.lower(COALESCE(
				pg_catalog.current_setting('portfolio_audit.event_silent', true),
				'off'
			)) IN ('1', 'on', 'true')
				AND session_user = 'portfolio_migrator_login'
				AND pg_catalog.current_setting('role') = 'portfolio_migrator'
			THEN
				RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
			END IF;

			IF (
				audit_request_id IS NULL
				OR audit_trace_id IS NULL
				OR audit_actor_kind IS NULL
				OR audit_actor_id IS NULL
				OR audit_operation IS NULL
				OR audit_release_id IS NULL
			) THEN
				SELECT activation.mode
				INTO STRICT audit_mode
				FROM %1$I.database_audit_activation AS activation
				WHERE activation.singleton;
				IF audit_mode = 'compatibility' THEN
					audit_request_id := 'compatibility:' || transaction_identifier;
					audit_trace_id := 'compatibility:' || transaction_identifier;
					audit_actor_kind := 'legacy-database-session';
					audit_actor_id := pg_catalog.left(session_user, 160);
					audit_operation := 'compatibility-' || pg_catalog.lower(TG_OP);
					audit_correlation_id := NULL;
					audit_causation_id := NULL;
					audit_release_id := 'pre-audit-37abdbd7a15f';
					audit_assertion_digest := NULL;
				ELSE
					RAISE EXCEPTION USING
						ERRCODE = 'PDA01',
						MESSAGE = 'Portfolio mutation audit context is required';
				END IF;
			END IF;

			IF audit_assertion_digest IS NOT NULL
				AND audit_assertion_digest !~ '^[0-9a-f]{64}$'
			THEN
				RAISE EXCEPTION USING
					ERRCODE = 'PDA01',
					MESSAGE = 'Portfolio mutation authentication assertion digest is invalid';
			END IF;

			IF session_user = 'portfolio_migrator_login'
				AND pg_catalog.current_setting('role') = 'portfolio_migrator'
				AND NULLIF(
					pg_catalog.current_setting('portfolio_audit.compensation_of', true),
					''
				) IS NOT NULL
			THEN
				BEGIN
					compensated_audit_id := pg_catalog.current_setting(
						'portfolio_audit.compensation_of',
						true
					)::uuid;
				EXCEPTION WHEN invalid_text_representation THEN
					RAISE EXCEPTION USING
						ERRCODE = 'PDA01',
						MESSAGE = 'Portfolio compensation context is invalid';
				END;
			END IF;

			IF TG_NARGS < 1 THEN
				RAISE EXCEPTION 'database mutation audit trigger requires primary-key columns';
			END IF;
			FOR argument_index IN 0..TG_NARGS - 1 LOOP
				IF NOT source_value ? TG_ARGV[argument_index] THEN
					RAISE EXCEPTION 'database mutation audit key column is absent';
				END IF;
				key_value := key_value || pg_catalog.jsonb_build_object(
					TG_ARGV[argument_index],
					source_value -> TG_ARGV[argument_index]
				);
			END LOOP;

			IF TG_OP = 'UPDATE' THEN
				SELECT COALESCE(pg_catalog.array_agg(keys.key ORDER BY keys.key), '{}'::text[])
				INTO changed
				FROM (
					SELECT old_keys.key
					FROM pg_catalog.jsonb_object_keys(old_value) AS old_keys(key)
					UNION
					SELECT new_keys.key
					FROM pg_catalog.jsonb_object_keys(new_value) AS new_keys(key)
				) AS keys
				WHERE old_value -> keys.key IS DISTINCT FROM new_value -> keys.key;

				IF pg_catalog.cardinality(changed) = 0 THEN
					RETURN NEW;
				END IF;

				SELECT pg_catalog.jsonb_object_agg(columns.column_name, old_value -> columns.column_name ORDER BY columns.column_name)
				INTO before_value
				FROM pg_catalog.unnest(changed) AS columns(column_name);
				SELECT pg_catalog.jsonb_object_agg(columns.column_name, new_value -> columns.column_name ORDER BY columns.column_name)
				INTO after_value
				FROM pg_catalog.unnest(changed) AS columns(column_name);
			ELSIF TG_OP = 'INSERT' THEN
				SELECT pg_catalog.array_agg(keys.key ORDER BY keys.key)
				INTO changed
				FROM pg_catalog.jsonb_object_keys(new_value) AS keys(key);
				before_value := NULL;
				after_value := new_value;
			ELSE
				SELECT pg_catalog.array_agg(keys.key ORDER BY keys.key)
				INTO changed
				FROM pg_catalog.jsonb_object_keys(old_value) AS keys(key);
				before_value := old_value;
				after_value := NULL;
			END IF;

			before_hash := pg_catalog.encode(
				pg_catalog.sha256(pg_catalog.convert_to(COALESCE(before_value::text, 'null'), 'UTF8')),
				'hex'
			);
			after_hash := pg_catalog.encode(
				pg_catalog.sha256(pg_catalog.convert_to(COALESCE(after_value::text, 'null'), 'UTF8')),
				'hex'
			);
			before_redacted_value := CASE WHEN before_value IS NULL THEN NULL ELSE
				pg_catalog.jsonb_build_object(
					'rowKey', key_value,
					'fields', pg_catalog.to_jsonb(changed)
				)
			END;
			after_redacted_value := CASE WHEN after_value IS NULL THEN NULL ELSE
				pg_catalog.jsonb_build_object(
					'rowKey', key_value,
					'fields', pg_catalog.to_jsonb(changed)
				)
			END;

			SELECT head_hash
			INTO prior_hash
			FROM %1$I.database_audit_chain_heads
			WHERE chain_name = 'portfolio'
			FOR UPDATE;
			IF prior_hash IS NULL THEN
				RAISE EXCEPTION 'Portfolio database audit chain head is missing';
			END IF;

			SELECT pg_catalog.nextval(
				pg_catalog.pg_get_serial_sequence('%1$I.database_mutation_audit', 'sequence_number')::regclass
			)
			INTO sequence_identifier;

			calculated_hash := pg_catalog.encode(
				pg_catalog.sha256(pg_catalog.convert_to(pg_catalog.jsonb_build_object(
					'previousHash', prior_hash,
					'auditId', audit_identifier::text,
					'sequenceNumber', sequence_identifier,
					'transactionId', transaction_identifier,
					'schemaName', TG_TABLE_SCHEMA,
					'tableName', TG_TABLE_NAME,
					'operation', TG_OP,
					'rowKey', key_value,
					'changedColumns', pg_catalog.to_jsonb(changed),
					'beforeDigest', before_hash,
					'afterDigest', after_hash,
					'databaseSessionUser', session_user::text,
					'databaseCurrentUser', pg_catalog.current_setting('role'),
					'requestId', audit_request_id,
					'traceId', audit_trace_id,
					'actorKind', audit_actor_kind,
					'actorId', audit_actor_id,
					'operationContext', audit_operation,
					'correlationId', audit_correlation_id,
					'causationId', audit_causation_id,
					'releaseId', audit_release_id,
					'authenticationAssertionDigest', audit_assertion_digest,
					'compensationOf', compensated_audit_id,
					'occurredAt', pg_catalog.to_char(
						occurred AT TIME ZONE 'UTC',
						'YYYY-MM-DD"T"HH24:MI:SS.US"Z"'
					)
				)::text, 'UTF8')),
				'hex'
			);

			INSERT INTO %1$I.database_mutation_audit (
				audit_id,
				sequence_number,
				transaction_id,
				schema_name,
				table_name,
				operation,
				row_key,
				changed_columns,
				before_redacted,
				after_redacted,
				before_digest,
				after_digest,
				database_session_user,
				database_current_user,
				request_id,
				trace_id,
				actor_kind,
				actor_id,
				operation_context,
				correlation_id,
				causation_id,
				release_id,
				authentication_assertion_digest,
				compensation_of,
				previous_hash,
				entry_hash,
				occurred_at
			) VALUES (
				audit_identifier,
				sequence_identifier,
				transaction_identifier,
				TG_TABLE_SCHEMA,
				TG_TABLE_NAME,
				TG_OP,
				key_value,
				changed,
				before_redacted_value,
				after_redacted_value,
				before_hash,
				after_hash,
				session_user::text,
				pg_catalog.current_setting('role'),
				audit_request_id,
				audit_trace_id,
				audit_actor_kind,
				audit_actor_id,
				audit_operation,
				audit_correlation_id,
				audit_causation_id,
				audit_release_id,
				audit_assertion_digest,
				compensated_audit_id,
				prior_hash,
				calculated_hash,
				occurred
			);

			DELETE FROM %1$I.database_compensation_payloads
			WHERE expires_at <= occurred;
			INSERT INTO %1$I.database_compensation_payloads (
				audit_id,
				before_state,
				after_state,
				created_at,
				expires_at
			) VALUES (
				audit_identifier,
				before_value,
				after_value,
				occurred,
				occurred + interval '7 days'
			);

			UPDATE %1$I.database_audit_chain_heads
			SET
				head_hash = calculated_hash,
				entry_count = entry_count + 1,
				updated_at = occurred
			WHERE chain_name = 'portfolio';

			RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
		END
		$function$
	$ddl$, target_schema);

	-- The only production logging surface is a chain-head summary. It exposes
	-- no row key, payload, actor, request, or compensation material.
	EXECUTE pg_catalog.format($ddl$
		CREATE FUNCTION %1$I.database_audit_chain_summary()
		RETURNS TABLE (
			chain_name text,
			head_hash text,
			entry_count bigint,
			last_sequence_number bigint,
			updated_at timestamp with time zone
		)
		LANGUAGE sql
		STABLE
		SECURITY DEFINER
		SET search_path = pg_catalog
		SET TimeZone = 'UTC'
		AS $function$
			SELECT
				head.chain_name,
				head.head_hash,
				head.entry_count,
				COALESCE((SELECT max(audit.sequence_number) FROM %1$I.database_mutation_audit AS audit), 0),
				head.updated_at
			FROM %1$I.database_audit_chain_heads AS head
			WHERE head.chain_name = 'portfolio'
		$function$
	$ddl$, target_schema);

	EXECUTE pg_catalog.format($ddl$
		CREATE FUNCTION %1$I.compensate_database_mutation(
			requested_audit_id uuid,
			expected_current_digest text
		)
		RETURNS uuid
		LANGUAGE plpgsql
		SECURITY DEFINER
		SET search_path = pg_catalog
		SET TimeZone = 'UTC'
		AS $function$
		DECLARE
			target %1$I.database_mutation_audit%%ROWTYPE;
			rollback_payload %1$I.database_compensation_payloads%%ROWTYPE;
			current_value jsonb;
			current_projection jsonb;
			calculated_current_digest text;
			set_clause text;
			affected_rows integer;
			compensation_audit_id uuid;
			compensation_request_id text := 'compensation:' || pg_catalog.gen_random_uuid()::text;
		BEGIN
			IF session_user <> 'portfolio_migrator_login'
				OR current_user <> 'portfolio_compensation_operator' THEN
				RAISE EXCEPTION USING
					ERRCODE = 'PDA04',
					MESSAGE = 'database compensation requires the dedicated Portfolio compensation boundary';
			END IF;
			IF pg_catalog.lower(COALESCE(
				pg_catalog.current_setting('portfolio_audit.event_silent', true),
				'off'
			)) IN ('1', 'on', 'true') THEN
				RAISE EXCEPTION USING
					ERRCODE = 'PDA04',
					MESSAGE = 'database compensation cannot run event-silent';
			END IF;

			SELECT *
			INTO target
			FROM %1$I.database_mutation_audit
			WHERE audit_id = requested_audit_id;
			IF NOT FOUND THEN
				RAISE EXCEPTION USING
					ERRCODE = 'PDA01',
					MESSAGE = 'database compensation audit target does not exist';
			END IF;
			IF expected_current_digest !~ '^[0-9a-f]{64}$'
				OR expected_current_digest <> target.after_digest
			THEN
				RAISE EXCEPTION USING
					ERRCODE = 'PDA01',
					MESSAGE = 'database compensation expected digest does not match the audited after-state';
			END IF;
			SELECT payload.*
			INTO rollback_payload
			FROM %1$I.database_compensation_payloads AS payload
			WHERE payload.audit_id = target.audit_id
				AND payload.expires_at > pg_catalog.clock_timestamp();
			IF NOT FOUND THEN
				RAISE EXCEPTION USING
					ERRCODE = 'PDA06',
					MESSAGE = 'database compensation rollback payload is absent or expired';
			END IF;

			EXECUTE pg_catalog.format(
				'SELECT pg_catalog.to_jsonb(candidate) FROM %%I.%%I AS candidate WHERE pg_catalog.to_jsonb(candidate) @> $1 FOR UPDATE',
				target.schema_name,
				target.table_name
			)
			INTO current_value
			USING target.row_key;

			IF current_value IS NULL THEN
				current_projection := NULL;
			ELSIF target.operation = 'UPDATE' THEN
				SELECT pg_catalog.jsonb_object_agg(
					columns.column_name,
					current_value -> columns.column_name
					ORDER BY columns.column_name
				)
				INTO current_projection
				FROM pg_catalog.unnest(target.changed_columns) AS columns(column_name);
			ELSE
				current_projection := current_value;
			END IF;

			calculated_current_digest := pg_catalog.encode(
				pg_catalog.sha256(pg_catalog.convert_to(
					COALESCE(current_projection::text, 'null'),
					'UTF8'
				)),
				'hex'
			);
			IF calculated_current_digest <> target.after_digest THEN
				RAISE EXCEPTION USING
					ERRCODE = 'PDA02',
					MESSAGE = 'database compensation refused because the current row digest or state differs';
			END IF;

			IF EXISTS (
				SELECT 1
				FROM %1$I.database_mutation_audit AS later
				WHERE later.schema_name = target.schema_name
					AND later.table_name = target.table_name
					AND later.row_key = target.row_key
					AND later.sequence_number > target.sequence_number
					AND later.changed_columns && target.changed_columns
			) THEN
				RAISE EXCEPTION USING
					ERRCODE = 'PDA03',
					MESSAGE = 'database compensation refused because a later overlapping mutation exists';
			END IF;

			PERFORM pg_catalog.set_config('portfolio_audit.compensation_of', target.audit_id::text, true);
			PERFORM pg_catalog.set_config('portfolio_audit.request_id', compensation_request_id, true);
			PERFORM pg_catalog.set_config('portfolio_audit.trace_id', compensation_request_id, true);
			PERFORM pg_catalog.set_config('portfolio_audit.actor_kind', 'database-operator', true);
			PERFORM pg_catalog.set_config('portfolio_audit.actor_id', session_user::text, true);
			PERFORM pg_catalog.set_config('portfolio_audit.operation', 'compensate-database-mutation', true);
			PERFORM pg_catalog.set_config('portfolio_audit.correlation_id', target.request_id, true);
			PERFORM pg_catalog.set_config('portfolio_audit.causation_id', target.audit_id::text, true);
			PERFORM pg_catalog.set_config('portfolio_audit.release_id', 'database-operator', true);
			PERFORM pg_catalog.set_config('portfolio_audit.authentication_assertion_digest', '', true);

			IF target.operation = 'INSERT' THEN
				EXECUTE pg_catalog.format(
					'DELETE FROM %%I.%%I AS candidate WHERE pg_catalog.to_jsonb(candidate) @> $1',
					target.schema_name,
					target.table_name
				) USING target.row_key;
			ELSIF target.operation = 'DELETE' THEN
				EXECUTE pg_catalog.format(
					'INSERT INTO %%I.%%I SELECT * FROM pg_catalog.jsonb_populate_record(NULL::%%I.%%I, $1)',
					target.schema_name,
					target.table_name,
					target.schema_name,
					target.table_name
				) USING rollback_payload.before_state;
			ELSE
				SELECT pg_catalog.string_agg(
					pg_catalog.format('%%1$I = restored.%%1$I', columns.column_name),
					', '
					ORDER BY columns.column_name
				)
				INTO set_clause
				FROM pg_catalog.unnest(target.changed_columns) AS columns(column_name);

				EXECUTE pg_catalog.format(
					'UPDATE %%I.%%I AS current_row SET %%s FROM (SELECT * FROM pg_catalog.jsonb_populate_record(NULL::%%I.%%I, $1)) AS restored WHERE pg_catalog.to_jsonb(current_row) @> $2',
					target.schema_name,
					target.table_name,
					set_clause,
					target.schema_name,
					target.table_name
				) USING rollback_payload.before_state, target.row_key;
			END IF;

			GET DIAGNOSTICS affected_rows = ROW_COUNT;
			IF affected_rows <> 1 THEN
				RAISE EXCEPTION USING
					ERRCODE = 'PDA05',
					MESSAGE = 'database compensation did not mutate exactly one row';
			END IF;

			SELECT audit_id
			INTO compensation_audit_id
			FROM %1$I.database_mutation_audit
			WHERE compensation_of = target.audit_id
				AND transaction_id = pg_catalog.pg_current_xact_id()::text
			ORDER BY sequence_number DESC
			LIMIT 1;
			IF compensation_audit_id IS NULL THEN
				RAISE EXCEPTION USING
					ERRCODE = 'PDA05',
					MESSAGE = 'database compensation did not create a new audited mutation';
			END IF;
			RETURN compensation_audit_id;
		END
		$function$
	$ddl$, target_schema);

	EXECUTE pg_catalog.format($ddl$
		CREATE FUNCTION %1$I.record_database_audit_release(
			p_release_sha text,
			p_image_digest text
		)
		RETURNS text
		LANGUAGE plpgsql
		SECURITY DEFINER
		SET search_path = pg_catalog
		SET TimeZone = 'UTC'
		AS $function$
		DECLARE
			activation %1$I.database_audit_activation%%ROWTYPE;
			release_time timestamp with time zone;
		BEGIN
			IF session_user <> 'portfolio_migrator_login'
				OR p_release_sha !~ '^[0-9a-f]{40}$'
				OR p_image_digest !~ '^sha256:[0-9a-f]{64}$'
			THEN
				RAISE EXCEPTION USING
					ERRCODE = 'PDA06',
					MESSAGE = 'Portfolio audit release evidence is invalid or unauthorized';
			END IF;

			INSERT INTO %1$I.database_audit_releases (release_sha, image_digest)
			VALUES (p_release_sha, p_image_digest)
			ON CONFLICT (release_sha) DO NOTHING;
			SELECT successful_at
			INTO STRICT release_time
			FROM %1$I.database_audit_releases
			WHERE release_sha = p_release_sha
				AND image_digest = p_image_digest;

			UPDATE %1$I.database_audit_activation
			SET compatibility_started_at = release_time,
				compatibility_release_sha = p_release_sha
			WHERE singleton
				AND compatibility_started_at IS NULL
				AND compatibility_release_sha IS NULL;

			SELECT * INTO STRICT activation
			FROM %1$I.database_audit_activation
			WHERE singleton
			FOR UPDATE;
			IF activation.mode = 'compatibility'
				AND activation.compatibility_started_at IS NOT NULL
				AND activation.compatibility_release_sha IS NOT NULL
				AND p_release_sha <> activation.compatibility_release_sha
				AND release_time >= activation.compatibility_started_at + interval '48 hours'
				AND EXISTS (
					SELECT 1
					FROM %1$I.database_audit_releases AS later_release
					WHERE later_release.release_sha = p_release_sha
						AND later_release.successful_at > activation.compatibility_started_at
				)
			THEN
				UPDATE %1$I.database_audit_activation
				SET mode = 'enforced',
					enforced_at = release_time,
					enforced_release_sha = p_release_sha
				WHERE singleton AND mode = 'compatibility';
			END IF;

			SELECT mode INTO STRICT activation.mode
			FROM %1$I.database_audit_activation
			WHERE singleton;
			RETURN activation.mode;
		END
		$function$
	$ddl$, target_schema);

	EXECUTE pg_catalog.format(
		'CREATE TRIGGER database_mutation_audit_immutable BEFORE INSERT OR UPDATE OR DELETE ON %I.database_mutation_audit FOR EACH ROW EXECUTE FUNCTION %I.unique_key_recheck()',
		target_schema,
		target_schema
	);
	EXECUTE pg_catalog.format(
		'CREATE TRIGGER database_mutation_audit_truncate_immutable BEFORE TRUNCATE ON %I.database_mutation_audit FOR EACH STATEMENT EXECUTE FUNCTION %I.unique_key_recheck()',
		target_schema,
		target_schema
	);
	EXECUTE pg_catalog.format(
		'CREATE TRIGGER database_audit_chain_heads_immutable BEFORE UPDATE OR DELETE ON %I.database_audit_chain_heads FOR EACH ROW EXECUTE FUNCTION %I.unique_key_recheck()',
		target_schema,
		target_schema
	);
	EXECUTE pg_catalog.format(
		'CREATE TRIGGER database_audit_chain_heads_truncate_immutable BEFORE TRUNCATE ON %I.database_audit_chain_heads FOR EACH STATEMENT EXECUTE FUNCTION %I.unique_key_recheck()',
		target_schema,
		target_schema
	);

	FOR relation_name, key_columns IN
		SELECT configured.relation_name, configured.key_columns
		FROM (VALUES
			('users', ARRAY['id']::text[]),
			('projects', ARRAY['id']::text[]),
			('ai_models', ARRAY['id']::text[]),
			('xyz_bullets', ARRAY['id']::text[]),
			('bio', ARRAY['id']::text[]),
			('bio_paragraphs', ARRAY['id']::text[]),
			('skills_group', ARRAY['id']::text[]),
			('all_skills', ARRAY['id']::text[]),
			('portfolio_skills', ARRAY['id']::text[]),
			('github_timeline_events', ARRAY['id']::text[]),
			('linkedin_timeline_events', ARRAY['id']::text[]),
			('personal_information', ARRAY['id']::text[]),
			('admin_policy_acceptance', ARRAY['id']::text[]),
			('education', ARRAY['id']::text[]),
			('experiences', ARRAY['id']::text[]),
			('browser_tracking', ARRAY['id']::text[]),
			('browser_tracking_ips', ARRAY['id']::text[]),
			('browser_request_logs', ARRAY['id']::text[]),
			('ip_rate_logs', ARRAY['id']::text[]),
			('welcome_messages', ARRAY['id']::text[]),
			('career_event_inbox', ARRAY['consumer', 'event_id']::text[]),
			('career_event_checkpoints', ARRAY['consumer', 'aggregate_id']::text[]),
			('career_event_quarantine', ARRAY['consumer', 'event_id', 'observed_digest']::text[])
		) AS configured(relation_name, key_columns)
	LOOP
		IF pg_catalog.to_regclass(pg_catalog.format('%I.%I', target_schema, relation_name)) IS NULL THEN
			RAISE EXCEPTION 'Portfolio audit target relation %.% is missing', target_schema, relation_name;
		END IF;
		SELECT pg_catalog.string_agg(pg_catalog.quote_literal(columns.column_name), ', ' ORDER BY columns.position)
		INTO trigger_arguments
		FROM pg_catalog.unnest(key_columns) WITH ORDINALITY AS columns(column_name, position);
		EXECUTE pg_catalog.format(
			'CREATE TRIGGER database_mutation_audit AFTER INSERT OR UPDATE OR DELETE ON %I.%I FOR EACH ROW EXECUTE FUNCTION %I.suppress_redundant_updates_trigger(%s)',
			target_schema,
			relation_name,
			target_schema,
			trigger_arguments
		);
		EXECUTE pg_catalog.format(
			'GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE %I.%I TO portfolio_compensation_operator',
			target_schema,
			relation_name
		);
	END LOOP;

	EXECUTE pg_catalog.format(
		'REVOKE ALL ON TABLE %I.database_mutation_audit, %I.database_audit_chain_heads, %I.database_compensation_payloads, %I.database_audit_activation, %I.database_audit_releases FROM PUBLIC',
		target_schema,
		target_schema,
		target_schema,
		target_schema,
		target_schema
	);
	EXECUTE pg_catalog.format(
		'REVOKE ALL ON FUNCTION %I.suppress_redundant_updates_trigger(), %I.unique_key_recheck(), %I.compensate_database_mutation(uuid, text), %I.database_audit_chain_summary(), %I.record_database_audit_release(text, text) FROM PUBLIC',
		target_schema,
		target_schema,
		target_schema,
		target_schema,
		target_schema
	);
	IF EXISTS (
		SELECT 1 FROM pg_catalog.pg_roles WHERE rolname = 'portfolio_runtime'
	) THEN
		EXECUTE pg_catalog.format(
			'REVOKE ALL ON TABLE %I.database_mutation_audit, %I.database_audit_chain_heads, %I.database_compensation_payloads, %I.database_audit_activation, %I.database_audit_releases FROM portfolio_runtime',
			target_schema,
			target_schema,
			target_schema,
			target_schema,
			target_schema
		);
		EXECUTE pg_catalog.format(
			'REVOKE ALL ON FUNCTION %I.suppress_redundant_updates_trigger(), %I.unique_key_recheck(), %I.compensate_database_mutation(uuid, text) FROM portfolio_runtime',
			target_schema,
			target_schema,
			target_schema
		);
		EXECUTE pg_catalog.format(
			'GRANT EXECUTE ON FUNCTION %I.database_audit_chain_summary() TO portfolio_runtime',
			target_schema
		);
	END IF;
	IF EXISTS (
		SELECT 1 FROM pg_catalog.pg_roles WHERE rolname = 'portfolio_migrator'
	) THEN
		EXECUTE pg_catalog.format(
			'GRANT EXECUTE ON FUNCTION %I.compensate_database_mutation(uuid, text) TO portfolio_migrator',
			target_schema
		);
		EXECUTE pg_catalog.format(
			'GRANT EXECUTE ON FUNCTION %I.record_database_audit_release(text, text) TO portfolio_migrator',
			target_schema
		);
	END IF;

	EXECUTE pg_catalog.format(
		'GRANT USAGE, CREATE ON SCHEMA %I TO portfolio_audit_owner, portfolio_compensation_operator',
		target_schema
	);
	EXECUTE pg_catalog.format(
		'GRANT SELECT ON TABLE %I.database_mutation_audit, %I.database_compensation_payloads TO portfolio_compensation_operator',
		target_schema,
		target_schema
	);
	EXECUTE pg_catalog.format(
		'ALTER TABLE %I.database_audit_chain_heads OWNER TO portfolio_audit_owner',
		target_schema
	);
	EXECUTE pg_catalog.format(
		'ALTER TABLE %I.database_mutation_audit OWNER TO portfolio_audit_owner',
		target_schema
	);
	EXECUTE pg_catalog.format(
		'ALTER TABLE %I.database_compensation_payloads OWNER TO portfolio_audit_owner',
		target_schema
	);
	EXECUTE pg_catalog.format(
		'ALTER TABLE %I.database_audit_activation OWNER TO portfolio_audit_owner',
		target_schema
	);
	EXECUTE pg_catalog.format(
		'ALTER TABLE %I.database_audit_releases OWNER TO portfolio_audit_owner',
		target_schema
	);
	EXECUTE pg_catalog.format(
		'ALTER FUNCTION %I.suppress_redundant_updates_trigger() OWNER TO portfolio_audit_owner',
		target_schema
	);
	EXECUTE pg_catalog.format(
		'ALTER FUNCTION %I.unique_key_recheck() OWNER TO portfolio_audit_owner',
		target_schema
	);
	EXECUTE pg_catalog.format(
		'ALTER FUNCTION %I.database_audit_chain_summary() OWNER TO portfolio_audit_owner',
		target_schema
	);
	EXECUTE pg_catalog.format(
		'ALTER FUNCTION %I.compensate_database_mutation(uuid, text) OWNER TO portfolio_compensation_operator',
		target_schema
	);
	EXECUTE pg_catalog.format(
		'ALTER FUNCTION %I.record_database_audit_release(text, text) OWNER TO portfolio_audit_owner',
		target_schema
	);
	EXECUTE pg_catalog.format(
		'REVOKE CREATE ON SCHEMA %I FROM portfolio_audit_owner, portfolio_compensation_operator',
		target_schema
	);
	PERFORM pg_catalog.set_config('role', audit_owner_role, true);
	EXECUTE pg_catalog.format(
		'ALTER DEFAULT PRIVILEGES IN SCHEMA %I REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC',
		target_schema
	);
	EXECUTE pg_catalog.format(
		'ALTER DEFAULT PRIVILEGES IN SCHEMA %I REVOKE ALL ON TABLES FROM PUBLIC',
		target_schema
	);
	EXECUTE pg_catalog.format(
		'ALTER DEFAULT PRIVILEGES IN SCHEMA %I REVOKE ALL ON SEQUENCES FROM PUBLIC',
		target_schema
	);
	PERFORM pg_catalog.set_config('role', 'portfolio_migrator', true);
	PERFORM pg_catalog.set_config('role', audit_operator_role, true);
	EXECUTE pg_catalog.format(
		'ALTER DEFAULT PRIVILEGES IN SCHEMA %I REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC',
		target_schema
	);
	PERFORM pg_catalog.set_config('role', migration_executor_role, true);
END
$migration$;
